/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import dominio.Jugador;
import dominio.Sistema;
import javax.swing.JOptionPane;
import javax.swing.JSpinner.DefaultEditor;

/**
 *
 * @author agustinintroini
 */
public class agregarJugador extends javax.swing.JFrame {

    /**
     * Creates new form agregarJugador
     */
    public agregarJugador() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        lblErrorNombre = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtAlias = new javax.swing.JTextField();
        lblErrorAlias = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        spinnerEdad = new javax.swing.JSpinner();
        btnAgregar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Agregar jugador");
        setAlwaysOnTop(true);
        setMinimumSize(new java.awt.Dimension(350, 200));
        setName("agregarJugador"); // NOI18N
        setPreferredSize(new java.awt.Dimension(350, 200));
        setResizable(false);
        setSize(new java.awt.Dimension(350, 200));
        getContentPane().setLayout(null);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Heiti SC", 0, 14)); // NOI18N
        jLabel1.setText("Nombre:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 17, -1, -1));

        txtNombre.setFont(new java.awt.Font("Heiti SC", 0, 13)); // NOI18N
        txtNombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtNombreMouseClicked(evt);
            }
        });
        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        jPanel1.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 12, 100, -1));

        lblErrorNombre.setFont(new java.awt.Font("Heiti SC", 0, 10)); // NOI18N
        lblErrorNombre.setForeground(new java.awt.Color(255, 51, 51));
        jPanel1.add(lblErrorNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 37, 110, 20));

        jLabel2.setFont(new java.awt.Font("Heiti SC", 0, 14)); // NOI18N
        jLabel2.setText("Alias:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 60, -1, -1));

        txtAlias.setFont(new java.awt.Font("Heiti SC", 0, 13)); // NOI18N
        txtAlias.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtAliasMouseClicked(evt);
            }
        });
        jPanel1.add(txtAlias, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 55, 100, -1));

        lblErrorAlias.setFont(new java.awt.Font("Heiti SC", 0, 10)); // NOI18N
        lblErrorAlias.setForeground(new java.awt.Color(255, 51, 51));
        jPanel1.add(lblErrorAlias, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 80, 110, 20));

        jLabel3.setFont(new java.awt.Font("Heiti SC", 0, 14)); // NOI18N
        jLabel3.setText("Edad:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 103, -1, 20));

        spinnerEdad.setFont(new java.awt.Font("Heiti SC", 0, 13)); // NOI18N
        spinnerEdad.setModel(new javax.swing.SpinnerNumberModel(6, 6, 120, 1));
        ((DefaultEditor) spinnerEdad.getEditor()).getTextField().setEditable(false);
        jPanel1.add(spinnerEdad, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, 52, -1));

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 10, 210, 150);

        btnAgregar.setFont(new java.awt.Font("Heiti TC", 0, 14)); // NOI18N
        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAgregar);
        btnAgregar.setBounds(230, 20, 100, 50);

        btnCancelar.setFont(new java.awt.Font("Heiti SC", 0, 14)); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancelar);
        btnCancelar.setBounds(230, 90, 100, 50);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
     Sistema sistema = new Sistema();
     String alias="", nombre="";
     int edad=(int)spinnerEdad.getValue();
        if(txtNombre.getText().isEmpty()){
          lblErrorNombre.setVisible(true);
          lblErrorNombre.setText("Ingrese un nombre");
      }else{
          nombre = txtNombre.getText();
      }
      //TODO:borrar jugador
        Jugador jugador1 = new Jugador("juan", "ote", 25);
       sistema.registrarJugador(jugador1);
      if(txtAlias.getText().isEmpty()){
          lblErrorAlias.setVisible(true);
          lblErrorAlias.setText("Ingrese un alias");
      }else if (null != sistema.buscarJugador(txtAlias.getText())){
          lblErrorAlias.setVisible(true);
          lblErrorAlias.setText("Alias en uso");
      }else{
          alias = txtAlias.getText();
         
          
      }
      if(!alias.isEmpty() && !nombre.isEmpty()){
          Jugador jugador = new Jugador(nombre, alias, edad);
          String [] botones = { "Agregar", "Cancelar"};
          if(JOptionPane.showOptionDialog (this, "¿Está seguro que desea agregar a este jugador?", "Agregar jugador", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE, null/*icono*/, botones, botones[0]) == 0) {
            
          sistema.registrarJugador(jugador);   
          }
          
      }
      
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void txtAliasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtAliasMouseClicked
               lblErrorAlias.setVisible(false);

    }//GEN-LAST:event_txtAliasMouseClicked

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed

    }//GEN-LAST:event_txtNombreActionPerformed

    private void txtNombreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNombreMouseClicked
        lblErrorNombre.setVisible(false);
    }//GEN-LAST:event_txtNombreMouseClicked

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
      
     
       
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(agregarJugador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(agregarJugador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(agregarJugador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(agregarJugador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new agregarJugador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblErrorAlias;
    private javax.swing.JLabel lblErrorNombre;
    private javax.swing.JSpinner spinnerEdad;
    private javax.swing.JTextField txtAlias;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
