package interfaz;

import dominio.Jugador;
import dominio.Sistema;
import javax.swing.JOptionPane;
import javax.swing.JSpinner.DefaultEditor;

/*
 * Creado por:
 *   Juan Balian - 211150
 *   Agustín Introini - 211064
 * */
public class AgregarJugador extends javax.swing.JFrame {
    Interfaz interfaz;

    public AgregarJugador(Interfaz interfaz) {
        initComponents();
        this.interfaz = interfaz;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblErrorNombre1 = new javax.swing.JLabel();
        lblErrorAlias1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        lblName = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtAlias = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        spinnerEdad = new javax.swing.JSpinner();
        lblErrorNombre = new javax.swing.JLabel();
        lblErrorAlias = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btnAgregar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();

        lblErrorNombre1.setFont(new java.awt.Font("Heiti SC", 0, 10)); // NOI18N
        lblErrorNombre1.setForeground(new java.awt.Color(255, 51, 51));
        lblErrorNombre1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        lblErrorAlias1.setFont(new java.awt.Font("Heiti SC", 0, 10)); // NOI18N
        lblErrorAlias1.setForeground(new java.awt.Color(255, 51, 51));
        lblErrorAlias1.setText("error");
        lblErrorAlias1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        lblErrorAlias1.setVisible(false);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);
        setBackground(Interfaz.colorFondo);
        setBounds(new java.awt.Rectangle(0, 23, 330, 275));
        setMaximumSize(new java.awt.Dimension(330, 275));
        setMinimumSize(new java.awt.Dimension(330, 275));
        setName("agregarJugador"); // NOI18N
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(330, 275));
        setResizable(false);
        setSize(new java.awt.Dimension(330, 275));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });
        getContentPane().setLayout(null);

        jPanel2.setBackground(Interfaz.colorFondo);
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(Interfaz.colorBotonesVacios));
        jPanel2.setLayout(null);

        jPanel1.setBackground(Interfaz.colorFondo);

        lblName.setFont(new java.awt.Font("Heiti SC", 0, 14)); // NOI18N
        lblName.setForeground(new java.awt.Color(255, 255, 255));
        lblName.setText("Nombre:");

        txtNombre.setFont(new java.awt.Font("Heiti SC", 0, 13)); // NOI18N
        txtNombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtNombreMouseClicked(evt);
            }
        });
        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Heiti SC", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Alias:");

        txtAlias.setFont(new java.awt.Font("Heiti SC", 0, 13)); // NOI18N
        txtAlias.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtAliasMouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Heiti SC", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Edad:");

        spinnerEdad.setFont(new java.awt.Font("Heiti SC", 0, 13)); // NOI18N
        spinnerEdad.setModel(new javax.swing.SpinnerNumberModel(6, 6, 120, 1));
        ((DefaultEditor) spinnerEdad.getEditor()).getTextField().setEditable(false);

        lblErrorNombre.setVisible(false);
        lblErrorNombre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/multimedia/icons8-high_importance.png"))); // NOI18N

        lblErrorAlias.setVisible(false);
        lblErrorAlias.setIcon(new javax.swing.ImageIcon(getClass().getResource("/multimedia/icons8-high_importance.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(lblName)
                    .addComponent(jLabel2))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(spinnerEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtAlias, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                            .addComponent(txtNombre, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblErrorNombre)
                            .addComponent(lblErrorAlias))))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblErrorNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(txtAlias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblErrorAlias, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(spinnerEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0))
        );

        jPanel2.add(jPanel1);
        jPanel1.setBounds(30, 60, 270, 110);

        jPanel3.setBackground(Interfaz.colorFondo);
        jPanel3.setLayout(new java.awt.GridLayout(1, 2, 10, 0));

        btnAgregar.setFont(new java.awt.Font("Heiti TC", 0, 14)); // NOI18N
        btnAgregar.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/multimedia/icons8-add_user.png"))); // NOI18N
        btnAgregar.setText("Agregar");
        btnAgregar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        btnAgregar.setContentAreaFilled(false);
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        jPanel3.add(btnAgregar);

        btnCancelar.setFont(new java.awt.Font("Heiti SC", 0, 14)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/multimedia/icons8-cancel.png"))); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        btnCancelar.setContentAreaFilled(false);
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        jPanel3.add(btnCancelar);

        jPanel2.add(jPanel3);
        jPanel3.setBounds(20, 200, 280, 60);

        jPanel5.setBackground(Interfaz.colorBarra);
        jPanel5.setPreferredSize(new java.awt.Dimension(500, 50));
        jPanel5.setLayout(null);

        jLabel4.setBackground(Interfaz.colorBarra);
        jLabel4.setFont(new java.awt.Font("Heiti TC", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Agregar jugador");
        jPanel5.add(jLabel4);
        jLabel4.setBounds(0, 0, 330, 50);

        jPanel2.add(jPanel5);
        jPanel5.setBounds(0, 0, 330, 50);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 330, 275);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        Sistema sistema = interfaz.getSistema();
        String alias = "", nombre = "";
        int edad= (int) spinnerEdad.getValue();
        if(txtNombre.getText().trim().isEmpty()){
            lblErrorNombre.setVisible(true);
            lblErrorNombre.setToolTipText("Ingrese un nombre");
        }
        else{
            nombre = txtNombre.getText();
        }
      
        if(txtAlias.getText().trim().isEmpty()){
            lblErrorAlias.setVisible(true);
            lblErrorAlias.setToolTipText("Ingrese un alias");
        }
        else if (null != sistema.buscarJugador(txtAlias.getText())){
            lblErrorAlias.setVisible(true);
            lblErrorAlias.setToolTipText("Alias en uso");
        }
        else{
            alias = txtAlias.getText();
        }
        if(!alias.isEmpty() && !nombre.isEmpty()){
            Jugador jugador = new Jugador(nombre, alias, edad);
            String [] botones = { "Agregar", "Cancelar"};
            if(JOptionPane.showOptionDialog (this, "¿Está seguro que desea agregar a este jugador?", "Agregar jugador", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null/*icono*/, botones, botones[0]) == 0) {
                sistema.registrarJugador(jugador);   

                JOptionPane.showMessageDialog(this, "El jugador ha sido agregado exitosamente","Jugador agregado",JOptionPane.PLAIN_MESSAGE);
                interfaz.setEnabled(true);
                this.dispose();
            }
        }
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void txtAliasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtAliasMouseClicked
        lblErrorAlias.setVisible(false);
    }//GEN-LAST:event_txtAliasMouseClicked

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
    }//GEN-LAST:event_txtNombreActionPerformed

    private void txtNombreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNombreMouseClicked
        lblErrorNombre.setVisible(false);
    }//GEN-LAST:event_txtNombreMouseClicked

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        interfaz.setEnabled(true);
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
    }//GEN-LAST:event_formWindowClosed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel lblErrorAlias;
    private javax.swing.JLabel lblErrorAlias1;
    private javax.swing.JLabel lblErrorNombre;
    private javax.swing.JLabel lblErrorNombre1;
    private javax.swing.JLabel lblName;
    private javax.swing.JSpinner spinnerEdad;
    private javax.swing.JTextField txtAlias;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
