/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;


import dominio.Sistema;


/**
 *
 * @author agustinintroini
 */
public class NuevaPartida extends javax.swing.JFrame {
   
    public NuevaPartida() {
        initComponents();
        
        

                  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnG = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        rbTodasFichas = new javax.swing.JRadioButton();
        rbCantMov = new javax.swing.JRadioButton();
        rbUnaFicha = new javax.swing.JRadioButton();
        btnSalir = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnSalir1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Agregar jugador");
        setAlwaysOnTop(true);
        setBounds(new java.awt.Rectangle(0, 23, 500, 335));
        setMinimumSize(new java.awt.Dimension(500, 335));
        setName("agregarJugador"); // NOI18N
        setUndecorated(true);
        setResizable(false);
        setType(java.awt.Window.Type.POPUP);
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Heiti SC", 0, 14)); // NOI18N
        jLabel2.setText("Forma de terminar:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(20, 17, 140, 15);

        btnG.add(rbTodasFichas);
        rbTodasFichas.setFont(new java.awt.Font("Gurmukhi Sangam MN", 0, 13)); // NOI18N
        rbTodasFichas.setText("Alcanzar con todas las fichas el lado opuesto");
        jPanel1.add(rbTodasFichas);
        rbTodasFichas.setBounds(160, 70, 290, 23);

        btnG.add(rbCantMov);
        rbCantMov.setFont(new java.awt.Font("Gurmukhi Sangam MN", 0, 13)); // NOI18N
        rbCantMov.setText("Cantidad de movimientos");
        jPanel1.add(rbCantMov);
        rbCantMov.setBounds(160, 10, 180, 23);

        btnG.add(rbUnaFicha);
        rbUnaFicha.setFont(new java.awt.Font("Gurmukhi Sangam MN", 0, 13)); // NOI18N
        rbUnaFicha.setText("Alcanzar con una ficha el lado opuesto");
        jPanel1.add(rbUnaFicha);
        rbUnaFicha.setBounds(160, 40, 260, 23);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 80, 470, 110);

        btnSalir.setFont(new java.awt.Font("Heiti SC", 0, 14)); // NOI18N
        btnSalir.setText("Cancelar");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalir);
        btnSalir.setBounds(270, 280, 140, 40);

        jLabel4.setFont(new java.awt.Font("Heiti TC", 1, 24)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Nueva partida");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 20, 470, 30);

        jLabel1.setFont(new java.awt.Font("Heiti SC", 0, 16)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Deben existir al menos dos jugadores para iniciar la partida");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 150, 490, 30);

        btnSalir1.setFont(new java.awt.Font("Heiti SC", 0, 14)); // NOI18N
        btnSalir1.setText("Iniciar partida");
        btnSalir1.setEnabled(false);
        btnSalir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalir1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalir1);
        btnSalir1.setBounds(120, 280, 140, 40);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnSalir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalir1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSalir1ActionPerformed


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NuevaPartida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NuevaPartida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NuevaPartida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NuevaPartida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NuevaPartida().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btnG;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnSalir1;
    private static javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton rbCantMov;
    private javax.swing.JRadioButton rbTodasFichas;
    private javax.swing.JRadioButton rbUnaFicha;
    // End of variables declaration//GEN-END:variables
}
