package interfaz;

import dominio.Partida;
import java.util.ArrayList;
import java.util.Collections;
import javax.swing.table.DefaultTableModel;

/*
 * Creado por:
 *   Juan Balian - 211150
 *   Agustín Introini - 211064
 * */
public class ReplicarPartida extends javax.swing.JFrame {
    Interfaz interfaz;
    public ReplicarPartida(Interfaz interfaz) {
        initComponents();
        this.interfaz = interfaz;
        
        String[] nombreColumnas =  new String [] {
                "Jugador rojo", "Jugador azul", "Dia", "Hora"
        };
        
        ArrayList<Partida> partidas = interfaz.getSistema().getPartidas();
        String datos[][] = new String[partidas.size()][4];
        Collections.sort(partidas);

        if (!partidas.isEmpty()) {
            for (int i = 0; i < partidas.size(); i++) {
                datos[i][0] = partidas.get(i).getJugadores()[0].getAlias();
                datos[i][1] = partidas.get(i).getJugadores()[1].getAlias();
                datos[i][2] = partidas.get(i).getDia();
                datos[i][3] = partidas.get(i).getHora();
            }
        }
        
        jTable1.setModel(new DefaultTableModel(datos, nombreColumnas) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };

            @Override
            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            @Override
            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return false;
            }
        });
        jTable1.getTableHeader().setReorderingAllowed(false);
        
        for(int i = 0; i < jTable1.getColumnModel().getColumnCount(); ++i)
            jTable1.getColumnModel().getColumn(i).setResizable(false);
        
        if(interfaz.getSistema().getPartidas().isEmpty())
            jScrollPane1.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnReplicar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Agregar jugador");
        setAlwaysOnTop(true);
        setBounds(new java.awt.Rectangle(0, 23, 470, 230));
        setMinimumSize(new java.awt.Dimension(470, 230));
        setName("agregarJugador"); // NOI18N
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(470, 230));
        setResizable(false);
        setSize(new java.awt.Dimension(470, 230));
        setType(java.awt.Window.Type.POPUP);
        getContentPane().setLayout(null);

        jPanel2.setBackground(Interfaz.colorFondo);
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(Interfaz.colorBotonesVacios));
        jPanel2.setMaximumSize(new java.awt.Dimension(470, 230));
        jPanel2.setMinimumSize(new java.awt.Dimension(470, 230));
        jPanel2.setPreferredSize(new java.awt.Dimension(470, 230));
        jPanel2.setSize(new java.awt.Dimension(470, 230));
        jPanel2.setLayout(null);

        jScrollPane1.setBackground(Interfaz.colorFondo);
        jScrollPane1.setForeground(new java.awt.Color(255, 255, 255));

        jTable1.setBackground(Interfaz.colorFondo);
        jTable1.setFont(new java.awt.Font("Heiti SC", 0, 12)); // NOI18N
        jTable1.setForeground(new java.awt.Color(255, 255, 255));
        jTable1.setModel(new javax.swing.table.DefaultTableModel() {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setSelectionBackground(Interfaz.colorBarra);
        jScrollPane1.setViewportView(jTable1);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(20, 50, 430, 100);

        jLabel1.setBackground(Interfaz.colorFondo);
        jLabel1.setFont(new java.awt.Font("Heiti SC", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Aún no se ha jugado ninguna partida");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(0, 90, 470, 30);

        jPanel1.setBackground(Interfaz.colorFondo);
        jPanel1.setLayout(new java.awt.GridLayout(1, 2, 10, 0));

        btnReplicar.setFont(new java.awt.Font("Heiti SC", 0, 14)); // NOI18N
        btnReplicar.setForeground(new java.awt.Color(255, 255, 255));
        btnReplicar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/multimedia/icons8-rotate.png"))); // NOI18N
        btnReplicar.setText("Replicar");
        btnReplicar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        btnReplicar.setContentAreaFilled(false);
        btnReplicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReplicarActionPerformed(evt);
            }
        });
        jPanel1.add(btnReplicar);

        btnSalir.setFont(new java.awt.Font("Heiti SC", 0, 14)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(255, 255, 255));
        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/multimedia/icons8-cancel.png"))); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        btnSalir.setContentAreaFilled(false);
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        jPanel1.add(btnSalir);

        jPanel2.add(jPanel1);
        jPanel1.setBounds(110, 160, 230, 60);

        jPanel5.setBackground(Interfaz.colorBarra);
        jPanel5.setPreferredSize(new java.awt.Dimension(500, 50));
        jPanel5.setLayout(null);

        jLabel4.setBackground(Interfaz.colorBarra);
        jLabel4.setFont(new java.awt.Font("Heiti TC", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Replicar partida");
        jPanel5.add(jLabel4);
        jLabel4.setBounds(0, 0, 470, 50);

        jPanel2.add(jPanel5);
        jPanel5.setBounds(0, 0, 470, 50);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 470, 230);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        interfaz.setEnabled(true);
        dispose();
        
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnReplicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReplicarActionPerformed
        if(jTable1.getSelectedRow() == -1)
            return;
        
        Partida p = interfaz.getSistema().getPartidas().get(jTable1.getSelectedRow());
            
        interfaz.setEnabled(true);
        interfaz.replicar(p); 
        this.dispose();
    }//GEN-LAST:event_btnReplicarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnReplicar;
    private javax.swing.JButton btnSalir;
    private static javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
